# Generated by Django 5.1.1 on 2024-09-13 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=70, null=True)),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('context', models.TextField()),
            ],
        ),
    ]
