# Generated by Django 5.1.1 on 2024-09-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_login_delete_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='number',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='name',
            new_name='username',
        ),
    ]
