# Generated by Django 5.1.1 on 2024-09-28 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_number_login_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='singup',
        ),
    ]
