# Generated by Django 5.1.1 on 2024-09-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_login_singup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
