# Generated by Django 5.1.1 on 2024-09-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_singup_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='obt_marks',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='students',
            old_name='firstname',
            new_name='session',
        ),
        migrations.RemoveField(
            model_name='students',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='students',
            name='total_marks',
        ),
        migrations.RemoveField(
            model_name='students',
            name='username',
        ),
        migrations.AddField(
            model_name='students',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
