# Generated by Django 5.1.1 on 2024-09-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_obt_marks_students_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singup',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
