# Generated by Django 5.1.1 on 2024-10-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_studentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=70, null=True)),
                ('student_names', models.JSONField(default=list, help_text='Enter student names in JSON format')),
                ('subject', models.CharField(blank=True, max_length=70, null=True)),
                ('teacher', models.CharField(blank=True, max_length=70, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='studentclass',
        ),
    ]
