# Generated by Django 5.1.1 on 2024-10-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_classstudent_delete_studentclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(blank=True, max_length=70, null=True)),
                ('student_names', models.CharField(help_text='Enter student names separated by commas', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=70, null=True)),
                ('teacher', models.CharField(blank=True, max_length=70, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='ClassStudent',
        ),
    ]
